services:
  web:
    image: ${GOALS_IMAGE:-ghcr.io/danielmoessner/goals.danielmoessner.de:latest}
    restart: unless-stopped
    user: "999:33"
    network_mode: "host"
    command: ["gunicorn", "--chdir", "/django", "config.wsgi:application", "--bind", "127.0.0.1:8080", "--timeout", "240", "-w", "2"]
    volumes:
      - /home/goals.danielmoessner.de/tmp:/django/tmp