[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.local"

[tool.black]
line-length = 88

[tool.isort]
known_local_folder = ["apps", "config"]
profile = "black"

[project]
name = "goals.danielmoessner.de"
version = "0.0.0"
description = ""
authors = [
    {name = "danielmoessner", email = "code@danielmoessner.de"},
]
readme = "README.md"
license = {text = "NONE"}
dependencies = [
    "django==6.*",
    "black==26.*",
    "django-cors-headers==4.*",
    "django-debug-toolbar==6.*",
    "django-filebrowser-no-grappelli==4.0.*",
    "django-tinymce==5.*",
    "djlint==1.36.*",
    "isort==8.*",
    "pillow==12.*",
    "pytest-django==4.*",
    "pytz==2026.*",
    "ruff==0.*",
    "python-telegram-bot==22.*",
    "gunicorn==25.*",
]
requires-python = "==3.14.*"
