# Generated by Django 5.1.4 on 2025-01-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0009_alter_todo_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="notes",
        ),
        migrations.CreateModel(
            name="NotesTodo",
            fields=[
                (
                    "todo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todos.todo",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            bases=("todos.todo",),
        ),
    ]
