# Generated by Django 5.1.4 on 2025-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0010_remove_todo_notes_notestodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="notestodo",
            name="position",
            field=models.CharField(
                choices=[("TOP", "Top"), ("BOTTOM", "Bottom")],
                default="TOP",
                max_length=20,
            ),
        ),
    ]
