# Generated by Django 5.1.6 on 2025-02-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0011_notestodo_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repetitivetodo",
            name="repetitions",
        ),
    ]
