# Generated by Django 5.1.6 on 2025-06-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0014_alter_pipelinetodo_previous_alter_todo_user_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="telegram_user_tag",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
    ]
