# Generated by Django 5.1.6 on 2025-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0015_page_telegram_chat_id_page_telegram_user_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="telegram_user_tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
