# Generated by Django 5.1.6 on 2025-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0016_alter_page_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="messages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
