# Generated by Django 5.1.6 on 2025-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0017_page_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="notestodo",
            name="width",
            field=models.CharField(
                choices=[("NARROW", "Narrow"), ("MEDIUM", "Medium"), ("WIDE", "Wide")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
    ]
