app_remote_dir: /home/goals.danielmoessner.de

app_data_dir: /home/goals.danielmoessner.de/tmp

app_bind_ip: 127.0.0.1

app_port: 8080

app_domain: goals.danielmoessner.de

app_nginx_site_name: goals.danielmoessner.de

app_client_max_body_size: 50m

app_domain_aliases: []

app_certbot_webroot: /var/www/certbot

app_image_repo: ghcr.io/danielmoessner/goals.danielmoessner.de
